name: CI

on: [push, pull_request]

env:
  CI: true

permissions:
  contents: read

jobs:
  ci:
    name: Build, Test and Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Install clang for Windows
        if: runner.os == 'Windows'
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop install llvm --global

          # Scoop modifies the PATH so we make the modified PATH global.
          echo $env:PATH >> $env:GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20.18.0

      - name: Setup Docker
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0 
        if: runner.os == 'Linux'

      - name: Fetch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      # Skip macOS & Windows, cache there is slower
      - name: Restore node_modules cache for Linux
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build libllhttp.a
        shell: bash
        run: |
          make build/libllhttp.a

      - name: Build WebAssembly
        run: npm run build-wasm
        if: runner.os == 'Linux'

      - name: Run tests
        run: npm run test

      - name: Lint Code
        run: npm run lint
        if: runner.os == 'Linux'